server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: /var/lib/tomcat/certificate/keystore.p12
    key-store-password: livelove_2000
    key-alias: 1

spring:
  mvc:
    view:
      prefix: /templates/

logging:
  level:
    org:
      thymeleaf: DEBUG
